---
- name: Playbook for httpd installation
  hosts: all
  tasks:
    - name: Install httpd Package 
      yum:
        name: httpd
        state: present
    - name: Create Index.html file
      copy:
       content: "WELCOME TO  LEADS"
       dest: /var/www/html/index.html
    - name: Start and Enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes

